### ISSUE TITLE
important links broken

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares.org#12]
In the live version.

https://bitshares.org/download/

https://bitshares.org/technology/user-issued-assets/

need redirection to new pages or at least old page.

many thanks.

**Comment by dls-cipher** [comment]
- Download will be up today. 

- Technology pages are all ready to be deployed on Monday (new ones).

One-pager for Technology of soft-launch for the Event purpose was created in last 48 hours, never meant to stay there. You can check in repository. This was just a quick and minimalistic launch.

![2018-11-16_1308](https://user-images.githubusercontent.com/39482961/48600955-b6759b00-e9a0-11e8-9771-3b5d3ffa698e.png)

**Comment by oxarbitrage** [comment]
Thank you for the hard work, the 404 page now is better than it was yesterday as at least users are still inside the site, yesterday was a white page.

Nice to see download page coming today as i think is one of the most important links of bitshares.org.

**Comment by dls-cipher** [comment]
Many thanks Alfredo, much much appreciated.

Personally, I've made 2 horrible mistakes with:
- not doing public announcement for soft-launch, even though it was just as a purpose to not show very old and outdated website on event where we are Platinum sponsor and to present technology instead of DEX (actually didn't had time for public discussion and admit ).
- messed up nginx configuration after ssl deployment (I went for pre-configured "lemp" setup at ISP instead of bare node).

Regarding SEO, sitemap.xml was rebuilt yesterday and any authority will index only those 3 without returning any broken links. Ill post reports on PageSpeed, YahooSlow, and SEO checkup on Monday, with full configuration/setup disclosed.  

This issue will be closed once Download/ is sorted.

**Comment by abitmore** [comment]
@dls-cipher which source file is the download page? I didn't find it. When created a new release for bitshares-core or bitshares-ui, we need to send pull requests to this repository. BTW @oxarbitrage we need to update Git Flow of the bitshares-core repository when got the answer. And I think we need to notify UI team about this as well.

**Comment by dls-cipher** [comment]
@abitmore - Sorry for confusion, please! Since we were chopping website and re-designing it a lot for decentralized, most of work was done offline with no updates to the GitHub. 

Ill update forums and upload new files/content to the GitHub within 24 hours. As soon as done, i'll mark this as closed and referenced issue. 

Thanks.

**Comment by abitmore** [comment]
@dls-cipher thank you.

Just noticed there is a link to https://bitshares.org/technology/industrial-performance-and-scalability/ on the [Graphene Wiki](https://github.com/cryptonomex/graphene/wiki) which is now broken. We need to either update the wiki page or update this repository. The Graphene Wiki is referenced here: https://github.com/satoshilabs/slips/blob/master/slip-0048.md#references. Since it's related to this issue so I'm leaving this message here, if need to create a new issue please comment.

**Comment by dls-cipher** [comment]
@abitmore - Done on live.

Header menu is updated with new urls, and "Technology" sub-folder is lower case now.

![2018-11-23_1341](https://user-images.githubusercontent.com/39482961/48930828-8fc9de00-ef25-11e8-9cea-b593a085380b.png)

Today will be pushed rest of the work live and over the weekend ill ssh to github to remove/update the content of repository/branches.

Chee®s

**Comment by abitmore** [comment]
The link https://bitshares.org/technology/industrial-performance-and-scalability/ mentioned in my last comment is still showing 404, as well as the links mentioned in OP. The reason is the trailing `/`. Perhaps we can add a rewrite rule? I've edited the wiki.

**Comment by dls-cipher** [comment]
@abitmore - will add rewrite rule under the current one, no issues. Im using anyway another location for /technology/ folder and extension management.

Thanks and sorry one more time, I've tested yesterday without trailing slash (mostly focused on missing **-and** and lower-case, not at end of url :( ) and as such added them to the header menu.

**Comment by oxarbitrage** [comment]
please fix link: https://bitshares.org/technology/price-stable-cryptocurrencies/

it is linked from https://stablecoinindex.com/projects and probably others. all old links should be redirected, its important.

**Comment by oxarbitrage** [comment]
the above message is just because of the last `/, this is working: https://bitshares.org/technology/price-stable-cryptocurrencies

need to make it also work with the `/` at the end. thank you.

**Comment by dls-cipher** [comment]
> the above message is just because of the last `/, this is working: https://bitshares.org/technology/price-stable-cryptocurrencies
> 
> need to make it also work with the `/` at the end. thank you.

Done and live.
