### ISSUE TITLE
Documentation Links

### ISSUE THREAD

**Issue by ryanRfox** [bitshares/bitshares.org#13]
- [ ] Please add a link to [Developer Portal](https://dev.bitshares.org)
- [x] Please update text for link [How BitShares Works](https://how.bitshares.works)

**Comment by dls-cipher** [comment]
They are already there named as:
[Documentation](https://how.bitshares.works) and [Developers Integration Guide](https://dev.bitshares.works)

**Notice:** In your url Developer portal leads to dev.bitshares.org instead of dev.bitshares.works, and it isn't a portal but just a guide/documentation. I'll create an issue to be renamed, since portal is web interface where users can register, sign in, do something, and that is just documentation/informational page. 

![2018-11-21_1531_001](https://user-images.githubusercontent.com/39482961/48828611-c3302f80-eda2-11e8-943b-6cd5cbafb17a.png)
![2018-11-21_1531](https://user-images.githubusercontent.com/39482961/48828612-c3c8c600-eda2-11e8-8e55-45fad64636b7.png)

**Comment by dls-cipher** [comment]
@ryanRfox - Im closing this since bitshares.org development is now moving 100% to github. Hope resolved, if not - easy to re-open.
