### ISSUE TITLE
[Content: Technology] Industrial Performance and Scalability

### ISSUE THREAD

**Issue by dls-cipher** [bitshares/bitshares.org#3]
Page:  industrial-performance-scalability.html

- Subtitles
- Missing H2 Headings
- Replacement of 5th focused keyword
- Missing meta description (First paragraph of the Content)
- Update title default to "'PAGE TITLE' | BitShares Blockchain" from current "'PAGE TITLE' - Bitshares"
- Optimize the content to achieve 5th focused keyword as 'scalability'.
- Check for typos/grammar.

Notice:
Before actual work done provide specific requests if any needed.

**Comment by rsswlkr** [comment]
Working on now, and have prepared environment under my own repo for testing. 
1) readability and seo testing results 'before' 

[Before.zip](https://github.com/bitshares/bitshares.org/files/2534946/Before.zip)

**Comment by rsswlkr** [comment]
Now changing subtitles and H2 headings

**Comment by rsswlkr** [comment]
Ok, now missing meta and title update. Few instance of 'scalability' added. Needs to go into new template, will also do that. Now provide screens for basic improvements and pull request, issue still open 

Progress can be viewed here https://rsswlkr.github.io/bitshares.org/industrial-performance-scalability
Continue this issue in morning and create pull request when done

**Comment by dls-cipher** [comment]
Nice. 

Also, please check what's with the link at the bottom of the page and do we have that page on the website or not. I don't believe that bitshares.org will load anything from 2015 once we upload new website. 

![2018-11-01_1312](https://user-images.githubusercontent.com/39482961/47835728-f866e480-ddd7-11e8-8e88-fcc72c01870d.png)

**Comment by rsswlkr** [comment]
There are a number of articles at https://bitshares.org/blog/ 
If these will not be retained then the link can be removed. Otherwise it is good content for further reading.  

I just spent one hour on the following 2 items: 
Optimize the content to achieve 5th focused keyword as 'scalability'.
Check for typos/grammar.
I also simplified some sentences, and removed 'passive voice' in a few places. I then ran a few more tests and progress/results are in the zip file

[Progress.zip](https://github.com/bitshares/bitshares.org/files/2539452/Progress.zip)

**Comment by rsswlkr** [comment]
Main Title fixed as last item. 
google preview and detected keywords looking better, ready to be reviewed.
metas fixed. 
attached screens tell the story, finished work is at 
https://rsswlkr.github.io/bitshares.org/industrial-performance-scalability.html
i will create pull request shortly. 
[Archive.zip](https://github.com/bitshares/bitshares.org/files/2544706/Archive.zip)
