### ISSUE TITLE
Initital description

### ISSUE THREAD

**Issue by sschiessl-bcp** [bitshares/bitshares.org#71]
![image](https://user-images.githubusercontent.com/33128181/57211469-a732ea00-6fe0-11e9-8ee2-53e2815fee8c.png)

- [x] Replace stakeholder with core token holder everytwhere (if it should be somewhere else on the site)

**Comment by dls-cipher** [comment]
Not gonna be that easy changed. Home page will be updated later today, but entire website not. There is a page called `stakeholder-approved-funding` and entire SEO is focused on word `stakeholder`. Just replacing it with `core-token holder` is not fitting into proper readability or SEO scores. @rsswlkr will get new Issue/task for this one and draft has to be reviewed publicly, in order to prevent double spent of worker funds. 

Chee®s

**Comment by dls-cipher** [comment]
@sschiessl-bcp - Replaced on that specific part. Another mention of `stakeholder` appears on the homepage, but its direct quote from Daniel Larimer, so no editing possible. 

May be possible we rephrase his quote to our own and sign someone else there. Thoughts ?

Chee®s

**Comment by sschiessl-bcp** [comment]
If it's marked as quote no problem imo

**Comment by dls-cipher** [comment]
Then done. Will create separate issue for `stakeholder-approved-funding` page.
