### ISSUE TITLE
please change BitShares 3.0 - Protocol Upgrade Countdown

### ISSUE THREAD

**Issue by oxarbitrage** [bitshares/bitshares.org#75]
I tried to do it but it seems the problem is the `master` branch is out of sync with what it is displayed in the org site https://bitshares.org/
Code looks updated in last release.
https://github.com/bitshares/bitshares.org/blob/master/index.php#L50-L53

But view online source is:

```
            <h1 id="bts3timer" class="hidden-sm-down home-title" data-aos="fade-down"><span class="bts-color fw-700"></span></h1>
            <h1 id="bts3timer" class="hidden-md-up home-title" data-aos="fade-down"><span class="bts-color fw-700"></span></h1>
			<h2 class="hidden-sm-down home-sub-title fw-500" data-aos="fade-up"><span class="text-dark">BitShares 3.0 - Protocol Upgrade Countdown</span></h2>
			<h2 class="hidden-md-up home-sub-title fw-500" data-aos="fade-up"><span class="text-dark">BitShares 3.0 - Protocol Upgrade Countdown</span></h2>
```

If fixed, we can update the main page to 3.1.0.

**Comment by dls-cipher** [comment]
Entire thing went through a lot of optimizations done on server directly, since we couldn't follow/bench otherwise on-the-fly. All commits were submitted yesterday and all the work/changes are now visible/live (how `master` branch, that how https://bitshares.org ).

Sorry for all delays, more progress/detailed reporting coming on Forums.
