### ISSUE TITLE
Wrong doxygen link at the bottom

### ISSUE THREAD

**Issue by abitmore** [bitshares/bitshares.org#76]
The doxygen pages have been moved to https://doxygen.bitshares.org/ for a long time, but the link at the bottom of the home page is still https://bitshares.org/doxygen/ with no redirect.

**Comment by dls-cipher** [comment]
Master was not up2date since 3.0 launch, and my apologies for it. 
Had really long sprint of optimizations and tweaks on the server (demo/production - yesterday commit shows all), otherwise couldn't follow up the progress/benchmark. 

Things fixed.

- Redirect is working on a server level ( `http(s)://bitshares.org/doxygen/ -> https://doxygen.bitshares.org` )
- Links are updated in header/footer menus for `https://doxygen.bitshares.org`

**Comment by abitmore** [comment]
@dls-cipher redirect is not working, but showing 404 or 403 for me. I'm reopening this issue, will close after redirect is fixed.

**Comment by abitmore** [comment]
Redirect didn't work due to an old cache on my disk. Don't know why it still has effect.

```
Request URL: https://bitshares.org/doxygen/
Request Method: GET
Status Code: 301  (from disk cache)
Remote Address: 104.27.171.224:443
Referrer Policy: no-referrer-when-downgrade
```
```
cache-control: max-age=2592000
cf-ray: 4e00616f1fc1d6c9-FRA
content-type: text/html; charset=iso-8859-1
date: Sat, 01 Jun 2019 10:07:26 GMT
expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
expires: Mon, 01 Jul 2019 10:07:26 GMT
location: http://bitshares.org/403.shtml/
server: cloudflare
status: 301
```
